<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <DS64 Condition="'$(DS64)' == '' AND $([MSBuild]::IsOSPlatform('Windows'))">$(registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 298740@InstallLocation)\DedicatedServer64</DS64>
    <DS64 Condition="'$(DS64)' == '' AND !$([MSBuild]::IsOSPlatform('Windows'))">$(HOME)/.steam/steam/steamapps/common/SpaceEngineersDedicatedServer/DedicatedServer64</DS64>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/CometWorks.EntityViewer.Magnetar/ViewerReferenceFrame.cs" Link="ViewerReferenceFrame.cs" />
    <Reference Include="VRage.Math" HintPath="$(DS64)/VRage.Math.dll" />
  </ItemGroup>
</Project>
